# Generated by Django 5.0.6 on 2024-05-22 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_smart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='latitute',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='unidade_media',
            new_name='unidade_medida',
        ),
    ]
